/* Generated By:JavaCC: Do not edit this line. LCageTreeConstants.java Version 5.0 */
public interface LCageTreeConstants
{
  public int JJTLCAGE = 0;
  public int JJTMAIN = 1;
  public int JJTATRIBUICAO = 2;
  public int JJTMDECLARACAO = 3;
  public int JJTVARDECL = 4;
  public int JJTTIPO = 5;
  public int JJTSEQCOMANDOS = 6;
  public int JJTCOMANDO = 7;
  public int JJTATRIBUIR = 8;
  public int JJTLOOP = 9;
  public int JJTEXP = 10;
  public int JJTFATOR = 11;
  public int JJTLISTAEXP = 12;
  public int JJTLISTAEXP2 = 13;
  public int JJTEXP_LOGICAS = 14;
  public int JJTFATOR_LOGICO = 15;
  public int JJTLISTAEXP_LOGICO = 16;
  public int JJTLISTAEXP2_LOGICO = 17;
  public int JJTFUNC = 18;
  public int JJTLISTAARG = 19;
  public int JJTLISTAARG2 = 20;


  public String[] jjtNodeName = {
    "LCage",
    "Main",
    "Atribuicao",
    "Mdeclaracao",
    "VarDecl",
    "Tipo",
    "SeqComandos",
    "Comando",
    "Atribuir",
    "Loop",
    "Exp",
    "Fator",
    "ListaExp",
    "ListaExp2",
    "Exp_logicas",
    "Fator_logico",
    "ListaExp_logico",
    "ListaExp2_logico",
    "Func",
    "ListaArg",
    "ListaArg2",
  };
}
/* JavaCC - OriginalChecksum=1d035831c2380d5a38d3f3d826c5b899 (do not edit this line) */
