/* Generated By:JJTree&JavaCC: Do not edit this line. LCageConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LCageConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 5;
  /** RegularExpression Id. */
  int COMENTARIOS = 6;
  /** RegularExpression Id. */
  int COM = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int ACHAVES = 9;
  /** RegularExpression Id. */
  int FCHAVES = 10;
  /** RegularExpression Id. */
  int APARENT = 11;
  /** RegularExpression Id. */
  int FPARENT = 12;
  /** RegularExpression Id. */
  int VAR = 13;
  /** RegularExpression Id. */
  int PTOVIRGULA = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int WHILE = 16;
  /** RegularExpression Id. */
  int DO = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int PRINT = 19;
  /** RegularExpression Id. */
  int FUNCAO = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int FLOAT = 22;
  /** RegularExpression Id. */
  int BOOL = 23;
  /** RegularExpression Id. */
  int TRUE = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int VIRGULA = 26;
  /** RegularExpression Id. */
  int ATRIB = 27;
  /** RegularExpression Id. */
  int OP = 28;
  /** RegularExpression Id. */
  int OPL = 29;
  /** RegularExpression Id. */
  int LETRA = 30;
  /** RegularExpression Id. */
  int DIGITO = 31;
  /** RegularExpression Id. */
  int DIGITOS = 32;
  /** RegularExpression Id. */
  int LD = 33;
  /** RegularExpression Id. */
  int FSUB = 34;
  /** RegularExpression Id. */
  int FOP = 35;
  /** RegularExpression Id. */
  int EXPOP = 36;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 37;
  /** RegularExpression Id. */
  int TOKEN_NUMLIT = 38;
  /** RegularExpression Id. */
  int ID_INVALIDO = 39;
  /** RegularExpression Id. */
  int INVALIDO_LEXICO = 40;
  /** RegularExpression Id. */
  int INVALID_CONST = 41;
  /** RegularExpression Id. */
  int INVALID_CONSTANTE_CHAR = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMENTARIO>",
    "<COMENTARIOS>",
    "<COM>",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"cage\"",
    "\";\"",
    "\"if\"",
    "\"ncage\"",
    "\"do\"",
    "\"return\"",
    "\"print\"",
    "\"funCage\"",
    "\"icage\"",
    "\"fcage\"",
    "\"bcage\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "\":=\"",
    "<OP>",
    "<OPL>",
    "<LETRA>",
    "<DIGITO>",
    "<DIGITOS>",
    "<LD>",
    "<FSUB>",
    "<FOP>",
    "<EXPOP>",
    "<IDENTIFICADOR>",
    "<TOKEN_NUMLIT>",
    "<ID_INVALIDO>",
    "<INVALIDO_LEXICO>",
    "<INVALID_CONST>",
    "<INVALID_CONSTANTE_CHAR>",
  };

}
